#!/bin/sh

echo -n "Empty course site directory"
echo
rm -rf ~/sy18-19-lacs/*

echo -n "Copying courses directory"
echo
 
cp -r ~/curr/distribution/courses ~/sy18-19-lacs/

echo -n "Building course pages"
echo

racket -l errortrace -t my-build.rkt

echo -n "Copying contents of index directory"
echo

cp -r distribution/index/. ~/sy18-19-lacs/

cd ../sy18-19-lacs/

git add -A

git commit -m "updated site content"

git push
